"""
Core data models used across the entire trading system.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class OrderSide(str, Enum):
    BUY = "Buy"
    SELL = "Sell"


class OrderType(str, Enum):
    MARKET = "Market"
    LIMIT = "Limit"
    STOP = "Stop"
    STOP_LIMIT = "StopLimit"


class OrderStatus(str, Enum):
    PENDING = "Pending"
    SUBMITTED = "Submitted"
    FILLED = "Filled"
    PARTIALLY_FILLED = "PartiallyFilled"
    CANCELLED = "Cancelled"
    REJECTED = "Rejected"


class SignalAction(str, Enum):
    LONG_ENTRY = "long_entry"
    SHORT_ENTRY = "short_entry"
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    FLATTEN = "flatten"


class AccountPhase(str, Enum):
    EVAL = "EVAL"
    PERFORMANCE = "PERFORMANCE"


class AccountStatus(str, Enum):
    ACTIVE = "active"
    PAUSED = "paused"           # Temporarily paused (drawdown protection)
    DAILY_LIMIT = "daily_limit"  # Hit daily loss limit
    CRITICAL = "critical"        # Near max drawdown — no trading
    TERMINATED = "terminated"    # Failed — account lost
    PASSED = "passed"            # EVAL passed → moving to PERFORMANCE


class StrategyName(str, Enum):
    VWAP_REVERSION = "vwap_reversion"
    OPENING_RANGE_BREAKOUT = "opening_range_breakout"
    MOMENTUM_SCALP = "momentum_scalp"


class RiskLevel(str, Enum):
    NORMAL = "normal"
    REDUCED = "reduced"      # After drawdown warning
    MINIMAL = "minimal"      # After drawdown danger
    HALTED = "halted"        # After drawdown critical


@dataclass
class TradingSignal:
    """Signal generated by a strategy (Pine Script or internal)."""
    signal_id: str
    strategy: StrategyName
    instrument: str
    action: SignalAction
    price: float
    timestamp: datetime
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    contracts: int = 1
    confidence: float = 0.5       # 0-1, used for sizing decisions
    metadata: dict = field(default_factory=dict)


@dataclass
class Order:
    """An order to be placed or already placed on Tradovate."""
    order_id: Optional[str] = None
    account_id: str = ""
    instrument: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: int = 1
    price: Optional[float] = None
    stop_price: Optional[float] = None
    status: OrderStatus = OrderStatus.PENDING
    signal_id: Optional[str] = None
    filled_price: Optional[float] = None
    filled_quantity: int = 0
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Position:
    """A current open position in an account."""
    account_id: str
    instrument: str
    side: OrderSide
    quantity: int
    entry_price: float
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    opened_at: datetime = field(default_factory=datetime.utcnow)
    signal_id: Optional[str] = None


@dataclass
class AccountState:
    """Real-time state of a single trading account."""
    account_id: str
    phase: AccountPhase
    status: AccountStatus = AccountStatus.ACTIVE
    risk_level: RiskLevel = RiskLevel.NORMAL

    # Balance tracking
    starting_balance: float = 50000.0
    current_balance: float = 50000.0
    high_water_mark: float = 50000.0      # For trailing drawdown calc
    daily_pnl: float = 0.0
    total_pnl: float = 0.0

    # Drawdown tracking
    trailing_drawdown_remaining: float = 2500.0
    drawdown_used_pct: float = 0.0

    # Trading stats
    trades_today: int = 0
    trading_days: int = 0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0

    # Positions
    open_positions: list = field(default_factory=list)
    max_contracts_used_today: int = 0

    # Strategy assignment
    assigned_strategies: list = field(default_factory=list)
    copy_group: int = 0

    # Timestamps
    last_trade_time: Optional[datetime] = None
    last_update: datetime = field(default_factory=datetime.utcnow)


@dataclass
class PortfolioState:
    """Aggregate state across all accounts."""
    accounts: dict = field(default_factory=dict)  # account_id → AccountState
    total_daily_pnl: float = 0.0
    total_open_positions: int = 0
    accounts_active: int = 0
    accounts_paused: int = 0
    accounts_passed: int = 0
    accounts_terminated: int = 0
    last_update: datetime = field(default_factory=datetime.utcnow)


@dataclass
class WebhookPayload:
    """Parsed payload from a TradingView webhook alert."""
    token: str
    strategy: str
    action: str
    instrument: str
    price: float
    timestamp: str
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    confidence: Optional[float] = None
    contracts: Optional[int] = None
    metadata: dict = field(default_factory=dict)
